server {
    listen 9000;
    server_name localhost;

    location / {
        # Bura ÇOX vacibdir, qovluq yolu tam eyni olmalıdır
        root /var/www/html/softy-pinko-front-end;
        index index.html;
    }
}