FROM nginx:latest
# Faylları tapşırıqda tələb olunan yerə kopyalayırıq
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end
# Konfiqurasiyanı kopyalayırıq
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf